### ISSUE TITLE
cloud-aws 2.1.0 doesn't support elasticsearch 1.1.1

### ISSUE THREAD

**Issue by ejain** [elastic/elasticsearch-cloud-aws#74]
The cloud-aws 2.1.0 plugin seems to work fine with elasticsearch 1.1.0, but with 1.1.1 I get this error on startup:

```
2014-04-18 01:19:42,754 [INFO] node - [Skywalker] version[1.1.1], pid[22901], build[f1585f0/2014-04-16T14:27:12Z]
2014-04-18 01:19:42,767 [INFO] node - [Skywalker] initializing ...
2014-04-18 01:19:42,802 [INFO] plugins - [Skywalker] loaded [cloud-aws], sites []
2014-04-18 01:19:50,019 [ERROR] bootstrap - {1.1.1}: Initialization Failed ...
1) NoSuchMethodError[org.elasticsearch.gateway.blobstore.BlobStoreGateway.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/threadpool/ThreadPool;Lorg/elasticsearch/cluster/ClusterService;)V]
```
