### ISSUE TITLE
Cannot initialize on ES 1.1.0

### ISSUE THREAD

**Issue by devony** [elastic/elasticsearch-cloud-aws#67]
I am getting the following error initializing the latest RC1 plugin on ES 1.1.0. This works in ES 1.0.1 and also when no cloud-aws config is set.

[2014-03-26 14:46:07,372][ERROR][bootstrap                ] {1.1.0}: Initialization Failed ...
1) NoSuchMethodError[org.elasticsearch.discovery.zen.ZenDiscovery.<init>(Lorg/elasticsearch/common/settings/Settings;Lorg/elasticsearch/cluster/ClusterName;Lorg/elasticsearch/threadpool/ThreadPool;Lorg/elasticsearch/transport/TransportService;Lorg/elasticsearch/cluster/ClusterService;Lorg/elasticsearch/node/settings/NodeSettingsService;Lorg/elasticsearch/cluster/node/DiscoveryNodeService;Lorg/elasticsearch/discovery/zen/ping/ZenPingService;Lorg/elasticsearch/Version;)V]2) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]
